### ISSUE TITLE
pre-made tangent <hair>

### ISSUE THREAD

**Issue by StephanZ1212** [KH40-khoast40/MES40#1]
How to i create Miku Hair Tangent? i have been search it on internet and i dont found anything :") , i want something shiny like in the readme, im sorry for my bad english 
![image](https://user-images.githubusercontent.com/22832827/78828577-1a25bb80-7a0f-11ea-8b34-bbdc55fdefee.png)

**Comment by KH40-khoast40** [comment]
First of all, that feature in the shader is broken, even if it work, it only works when the model is in the default position (a-pose or t-pose, not rotated). If the model moves, the hightlight will break. There is no way to fix this (yet). So don't spend your time on this.

Even so, here is the solution to your question:

When you rip the model, you must use [minmode's pmx script](https://www.deviantart.com/minmode/art/Update-1-3-Noesis-PMX-VMD-export-809252773) to export the model **from .bin to .pmx** in noesis, any other method of ripping wouldn't work bc this is the only way for the model to store the tagents in its data. If you use that method of ripping, then just apply a spa on the hair, turn on the pre-made tangents option and it's done.

**Comment by StephanZ1212** [comment]
Ahh Okay, Thankyou for your response, i'll try it then
