### ISSUE TITLE
ExcellentShadow2 and alphatest conflict

### ISSUE THREAD

**Issue by cuongdq0511** [KH40-khoast40/MES40#2]
Some models from DIVA FT use the alphatest = 0 for some of their material. The issue is, with ExcellentShadow2 enabled, the shadow of the things lay behind the the material with alphatest = 0 still appear. This works fine with MMD shadow and beamman shadow.

![1](https://user-images.githubusercontent.com/63622164/79174175-171e3700-7e24-11ea-9a84-bd55d33da539.jpg)
![2](https://user-images.githubusercontent.com/63622164/79174189-1e454500-7e24-11ea-908e-f51929a58d37.jpg)

**Comment by cuongdq0511** [comment]
I can send your the model for reference if you need, thanks

**Comment by KH40-khoast40** [comment]
Yes please, and include the fx too

**Comment by cuongdq0511** [comment]
The alphatest=0 materials are pianep and piabousi

https://drive.google.com/open?id=1zrleOXGMAgR5BzfaSYqzEJPXTUlkuXhb

**Comment by KH40-khoast40** [comment]
When you want an object to be solid, you should use a genuinely solid texture, not by alphatest=1, the latter method while can make the object solid, but the shadow is unaffected so it still have the shadow of an transparent object, thus why you can see the shadow through it
 
Here is the fixed version of your model, just use a no alpha version of the texture on one of the overlapping objects https://drive.google.com/open?id=1PshZu_5vKLk4xRUBAPzWLdLCaPC5nYka

**Comment by cuongdq0511** [comment]
I got it, thanks.
But can you show me how to make a solid texture like you did?

**Comment by KH40-khoast40** [comment]
export the raw texture to jpg

**Comment by KH40-khoast40** [comment]
raw texture as in .bin
