### ISSUE TITLE
MMD Shadow System Effect Suggestion

### ISSUE THREAD

**Issue by Lilothestitch16** [KH40-khoast40/MES40#3]
Hi. is it possible to add a shader preset where the object is invisible but it's self shadow is visible based on these images for example for the MMD Extended Shader?
![Character Self Shadow](https://user-images.githubusercontent.com/8963276/87059422-4b14b880-c1d7-11ea-90b1-3cd41552d9ce.png)
![MMD Self Shadow](https://user-images.githubusercontent.com/8963276/87059426-4bad4f00-c1d7-11ea-9a38-88ae1fe07abd.png)
![Stage Shadow System](https://user-images.githubusercontent.com/8963276/87059431-4ea83f80-c1d7-11ea-89a1-481745d894eb.png)

**Comment by KH40-khoast40** [comment]
I remember answering this question to someone on the dA comment section, it's too specific of a request to be used by any cases other than the one you said. 
Beside, now thinking about it, I actually haven't got an idea on how to do that thing either. So sorry : (

**Comment by Lilothestitch16** [comment]
It's fine. Even I had trouble on how to do it. Is there a tutorial on how to make custom .fx files for MMD?

**Comment by KH40-khoast40** [comment]
I'm not sure, as far as I know, no. But you can search for articles about HLSL to begin learning about the shader language MMD uses
