### ISSUE TITLE
Suggestion: Shader to use 2 or more textures

### ISSUE THREAD

**Issue by Lilothestitch16** [KH40-khoast40/MES40#4]
Is it possible for the shader to use 2 or more different textures on the models?

**Comment by KH40-khoast40** [comment]
Vague question, if you mean for the 2 textures to blend together, you can use submap (with the same UV as the regular texture) for that

**Comment by Lilothestitch16** [comment]
How many sub maps can I use?

**Comment by KH40-khoast40** [comment]
Currently one
