### ISSUE TITLE
[Feature Requests] Water Effect, Blending Effect, and Environment Map Effect.

### ISSUE THREAD

**Issue by Lilothestitch16** [KH40-khoast40/MES40#5]
Is it possible to add these features to the shader like Water Effect, Blending Effect and Environment Map Effect? I'm working on Delfino Plaza from Super Mario Sunshine and I'm trying to get the skydome from the game to show how the game shows it.

Water Effect: ![Water Effect](https://user-images.githubusercontent.com/8963276/93835932-e6ea8800-fc4e-11ea-8a94-8529e467df61.png)

Blending Effect: ![Sky Blending](https://user-images.githubusercontent.com/8963276/93835951-f8339480-fc4e-11ea-9c96-2d3066da2cea.png)

Environment Map Effect: ![Environment Map Effect](https://user-images.githubusercontent.com/8963276/93836114-932c6e80-fc4f-11ea-8bbe-dbf632a656ab.png)

**Comment by KH40-khoast40** [comment]
The water effect can be fake by animated normal map, I'll add this feature sooner or latter

There are too many types of blending effect to be added

The cubemap is env map

**Comment by Lilothestitch16** [comment]
Then would it be possible to only add one blending effect then?

**Comment by KH40-khoast40** [comment]
Depend on which one it is

**Comment by Lilothestitch16** [comment]
I think it's the one that says Pixel Z <= EFB Z and Blending Calculation is Pixel Color* = 1 and EFB Color * = 1 - Pixel Color

**Comment by KH40-khoast40** [comment]
I dont really know how to translate it into mmd's shader language jeqiisjqosoekugg

**Comment by Lilothestitch16** [comment]
Does this shader have a mask texture effect?

**Comment by KH40-khoast40** [comment]
No, if the mask uses different UV than the base texture, it would need an extra UV, currently I think there is no program that can put the UV into slot 3 or 4 beside pmxe itself

If the mask uses the same UV as the base texture, you can always use photoshop to edit the mask into the base texture instead
