### ISSUE TITLE
cubemaps of... a single texture?

### ISSUE THREAD

**Issue by Sozuke** [KH40-khoast40/MES40#6]
Some unity models use textures that work as cubemaps but inside the corresponding texture there's only one image (it doesn't match what the shader needs to work) although in adduv there's uv mapping that maps the texture as it should be shown (when you add it as subtext it looks like the game but without the environment effect
example:
all are the same material

![PMXView 16_10_2020 07_16_52 p  m](https://user-images.githubusercontent.com/48562770/96323766-4173cb80-0fe4-11eb-8c88-717879fd60cc.png)

![PMXView 16_10_2020 07_17_09 p  m](https://user-images.githubusercontent.com/48562770/96323898-ab8c7080-0fe4-11eb-87cd-2a108e620eb7.png)

![PMXView 16_10_2020 07_17_29 p  m](https://user-images.githubusercontent.com/48562770/96323850-797b0e80-0fe4-11eb-946d-0d3bba5ecd4c.png)

I attach the corresponding textures

![hairh](https://user-images.githubusercontent.com/48562770/96323878-97e10a00-0fe4-11eb-8e70-5178d544cf34.png)
![hair](https://user-images.githubusercontent.com/48562770/96323879-9879a080-0fe4-11eb-87e3-f3e323d12f5b.png)

**Comment by KH40-khoast40** [comment]
I don't really get what you are trying to say bc I'm stranger to that kind of model. But if you want to make a cubemap from just 1 texture, you can use a cubemap making program and choose that texture for all 6 sides of the cubemap
