### ISSUE TITLE
Animated Normal Map Help

### ISSUE THREAD

**Issue by Lilothestitch16** [KH40-khoast40/MES40#7]
How do I get a normal map to be animated? I want to see if I can get this normal map to be animated so that I can make a water effect.
![model_32_0_0_93](https://user-images.githubusercontent.com/8963276/103498243-69700f80-4e1a-11eb-9c9a-5b9443e3bd56.png)

**Comment by KH40-khoast40** [comment]
Same way as you make normal texture animated

**Comment by Lilothestitch16** [comment]
Do I need a program to generate it or something? If so, what program would you recommend?

**Comment by KH40-khoast40** [comment]
If your normal map doesn't already has sequences to join to make it become animated like the water in PjD, then you have to figure it on your own

**Comment by Lilothestitch16** [comment]
What's PjD? Is that a program or something?

**Comment by KH40-khoast40** [comment]
Project Diva bruh

**Comment by Lilothestitch16** [comment]
Would Blender work for animated normal map or photoshop?

**Comment by KH40-khoast40** [comment]
As long as it can make png sequence to make apng

**Comment by Lilothestitch16** [comment]
Okay. I'll see what i can do.
