### ISSUE TITLE
[Feature Request] WrapModeX and WrapModeY with 1 for Repeat, 2 for Mirror and 3 for Clamp?

### ISSUE THREAD

**Issue by Lilothestitch16** [KH40-khoast40/MES40#8]
Would it be possible to add a feature to have WrapModeX and WrapModeY with 1 for Repeat, 2 for Mirror and 3 for Clamp for objects?

![image](https://user-images.githubusercontent.com/8963276/140625063-fd1bb59c-3696-4a48-8f74-448aa1f70ae7.png)

![image](https://user-images.githubusercontent.com/8963276/140625068-a6c2d0bd-6d87-493b-8715-c0532f40a3b2.png)

**Comment by KH40-khoast40** [comment]
An option like that is redundant for mmd models since most of them have their UVs baked to be used in one single wrap mode.

However you can change it yourself by edit this in the `sampler ObjTexSampler`:
```
ADDRESSU  = WRAP;
ADDRESSV  = WRAP;
```
Change the WRAP to whatever UV mode you like

**Comment by Lilothestitch16** [comment]
How do I do that? Any ideas?

**Comment by KH40-khoast40** [comment]
Just search for the `sampler ObjTexSampler` line in the MES40.fxsub, there'll be `ADDRESSU` and `ADDRESSV` under that

**Comment by Lilothestitch16** [comment]
And then? What do I use to change them?

**Comment by KH40-khoast40** [comment]
notepad, they are literally texts... change the "WRAP" to whatever mode you want (Repeat,clamp,mirror,...)

**Comment by Lilothestitch16** [comment]
Changed it to Mirror but nothing happened.

![image](https://user-images.githubusercontent.com/8963276/140954547-26323bd5-24a9-4566-952b-9e4928bf9374.png)

**Comment by KH40-khoast40** [comment]
weird, I can't do anything about it then

**Comment by Lilothestitch16** [comment]
Darn. I thought it would do something.

**Comment by Lilothestitch16** [comment]
It worked in PMX Editor. 
![image](https://user-images.githubusercontent.com/8963276/140956945-97c158a3-6f75-476f-a014-2c517b8bd47a.png)

**Comment by KH40-khoast40** [comment]
you mean that modification makes the shader works the way you want in pmxe?

**Comment by Lilothestitch16** [comment]
It worked. 
![image](https://user-images.githubusercontent.com/8963276/140957187-1072c4c3-777f-4b71-862b-eec15dd00078.png)

**Comment by KH40-khoast40** [comment]
good then
